arb-dir: lib/l10n
template-arb-file: app_zh.arb
output-localization-file: app_localizations.dart
output-class: AppLocalizations
output-dir: lib/gen_l10n
preferred-supported-locales: [zh]
nullable-getter: false
synthetic-package: false
