# MSIX 配置文件
# 用于生成Windows应用安装包

msix_config:
  # 应用基本信息
  display_name: "ThoughtEcho"
  publisher_display_name: "Shangjinyun"
  identity_name: "Shangjinyun.330094822087A"
  
  # 版本信息 - 将在CI中自动更新
  msix_version: 1.0.0.0
  
  # 发布者信息（Microsoft Store要求的发布者证书）
  # 注意：此为Microsoft Store分配的发布者标识
  publisher: "CN=14B607B9-7CF3-42D9-9054-090F3ECEC1D7"
  
  # 应用描述
  description: "一款帮助你记录和分析思想的应用"
  
  # 应用图标（Windows ICO格式）
  logo_path: "windows/runner/resources/app_icon.ico"
  
  # 启动任务
  start_menu_icon: "windows/runner/resources/app_icon.ico"
  tile_icon: "windows/runner/resources/app_icon.ico"
  
  # 所需权限
  # internetClient: 允许应用访问互联网
  # 注意：不要手动添加 runFullTrust，Flutter Windows 应用会自动添加
  #       手动添加会导致包标识不匹配问题
  capabilities: "internetClient"
  
  # 安装设置
  install_location: "custom"
  
  # 语言和本地化
  languages: "zh-CN,en-US"
  
  # 架构支持
  architecture: "x64"
  
  # 输出文件名
  output_name: "ThoughtEcho-Setup.msix"
  
  # ⚠️ 关键配置：禁用本地签名，让 Microsoft Store 自动签名
  # 本地签名会生成测试证书，导致 Publisher 不匹配
  # Store 提交时会自动使用正确的证书重新签名
  sign_msix: false
  
  # 签名设置（完全禁用本地证书）
  certificate_path: null
  certificate_password: null
  
  # 应用设置
  app_execution_alias: "thoughtecho"
  
  # CI/CD设置
  store_type: "defaultInstallLocation"
  install_certificate: false
  
  # 可视化资产
  visual_elements:
    display_name: "ThoughtEcho"
    description: "一款帮助你记录和分析思想的应用"
    background_color: "#2E7D32"
    show_name_on_square150x150_logo: true
    square150x150_logo: "windows/runner/resources/app_icon.ico"
    square44x44_logo: "windows/runner/resources/app_icon.ico"