# MSIX 配置文件
# 用于生成Windows应用安装包

msix_config:
  # 应用基本信息
  display_name: "ThoughtEcho"
  publisher_display_name: "ThoughtEcho Team"
  identity_name: "com.thoughtecho.app"
  
  # 版本信息 - 将在CI中自动更新
  msix_version: 1.0.0.0
  
  # 发布者信息（CI环境使用自动生成的测试证书）
  publisher: "CN=ThoughtEcho Team"
  
  # 应用描述
  description: "一款帮助你记录和分析思想的应用"
  
  # 应用图标（Windows ICO格式）
  logo_path: "windows/runner/resources/app_icon.ico"
  
  # 启动任务
  start_menu_icon: "windows/runner/resources/app_icon.ico"
  tile_icon: "windows/runner/resources/app_icon.ico"
  
  # 所需权限
  capabilities: "internetClient"
  
  # 安装设置
  install_location: "custom"
  
  # 语言和本地化
  languages: "zh-CN,en-US"
  
  # 架构支持
  architecture: "x64"
  
  # 输出文件名
  output_name: "ThoughtEcho-Setup.msix"
  
  # 签名设置（CI环境自动处理）
  certificate_path: null
  certificate_password: null
  
  # 应用设置
  app_execution_alias: "thoughtecho"
  
  # CI/CD设置 - 在非交互式环境中自动处理证书
  certificate_subject: "CN=ThoughtEcho Team"
  store_type: "defaultInstallLocation"
  
  # 可视化资产
  visual_elements:
    display_name: "ThoughtEcho"
    description: "一款帮助你记录和分析思想的应用"
    background_color: "#2E7D32"
    show_name_on_square150x150_logo: true
    square150x150_logo: "windows/runner/resources/app_icon.ico"
    square44x44_logo: "windows/runner/resources/app_icon.ico"