name: mind_trace
description: 一款帮助你记录和分析思想的应用。
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  sqflite: ^2.5.0
  sqflite_common_ffi: ^2.5.0
  sqlite3_flutter_libs: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.3
  http: ^1.2.1
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  flutter_markdown: ^0.7.1
  intl: ^0.19.1
  url_launcher: ^6.3.0
  file_picker: ^7.0.0
  # dynamic_color: ^1.7.2
  flex_color_scheme: ^7.5.0
  geolocator: ^12.0.0
  permission_handler: ^13.0.0
  weather: ^4.0.0
  flutter_secure_storage: ^10.0.0
  
  # 显式指定Kotlin版本
  kotlin:
    plugin: "1.9.22"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
# 字体配置
flutter:
  # 确保应用可以使用Material Design图标
  uses-material-design: true
  
  # 使用系统字体，不再需要额外的字体资源
  # fonts:
  #   - family: NotoSansSC
  #     fonts:
  #       - asset: assets/fonts/NotoSansSC-Regular.ttf
  #       - asset: assets/fonts/NotoSansSC-Bold.ttf
  #         weight: 700