// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/objectbox/note_vector.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 4873036037937112007),
    name: 'NoteVector',
    lastPropertyId: const obx_int.IdUid(8, 5223954551422734137),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 583031982135149259),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5658189281937610282),
        name: 'noteId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 4741312224834442472),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5955391040079459657),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(2, 3465174967330679272),
        hnswParams: obx_int.ModelHnswParams(dimensions: 384),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6339491108681561377),
        name: 'contentPreview',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4861150728252972701),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5254111361204892039),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 7378933207199825717),
        name: 'modelVersion',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5223954551422734137),
        name: 'dimension',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 2292889071168205162),
    name: 'SearchHistory',
    lastPropertyId: const obx_int.IdUid(6, 3673540137133467596),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7391343541600706259),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4396780360493048535),
        name: 'query',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2469274343896026857),
        name: 'queryEmbedding',
        type: 28,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 559155495213804399),
        name: 'searchedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3381511221066225534),
        name: 'resultCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3673540137133467596),
        name: 'hasClicked',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 7063434601830221067),
    name: 'SimilarNotesCache',
    lastPropertyId: const obx_int.IdUid(6, 4211624706151040871),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3451870795145100349),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6280352458237904014),
        name: 'sourceNoteId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 6440255065087885933),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2383116664870755875),
        name: 'similarNoteIdsJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 6667572752515274521),
        name: 'similarityScoresJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2070608722898331945),
        name: 'cachedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4211624706151040871),
        name: 'validHours',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 7063434601830221067),
    lastIndexId: const obx_int.IdUid(3, 6440255065087885933),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    NoteVector: obx_int.EntityDefinition<NoteVector>(
      model: _entities[0],
      toOneRelations: (NoteVector object) => [],
      toManyRelations: (NoteVector object) => {},
      getId: (NoteVector object) => object.id,
      setId: (NoteVector object, int id) {
        object.id = id;
      },
      objectToFB: (NoteVector object, fb.Builder fbb) {
        final noteIdOffset = fbb.writeString(object.noteId);
        final embeddingOffset = fbb.writeListFloat32(object.embedding);
        final contentPreviewOffset = object.contentPreview == null
            ? null
            : fbb.writeString(object.contentPreview!);
        final modelVersionOffset = fbb.writeString(object.modelVersion);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, noteIdOffset);
        fbb.addOffset(2, embeddingOffset);
        fbb.addOffset(3, contentPreviewOffset);
        fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(5, object.updatedAt.millisecondsSinceEpoch);
        fbb.addOffset(6, modelVersionOffset);
        fbb.addInt64(7, object.dimension);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final noteIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 8, []);
        final contentPreviewParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final updatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final modelVersionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final dimensionParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final object = NoteVector(
          id: idParam,
          noteId: noteIdParam,
          embedding: embeddingParam,
          contentPreview: contentPreviewParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          modelVersion: modelVersionParam,
          dimension: dimensionParam,
        );

        return object;
      },
    ),
    SearchHistory: obx_int.EntityDefinition<SearchHistory>(
      model: _entities[1],
      toOneRelations: (SearchHistory object) => [],
      toManyRelations: (SearchHistory object) => {},
      getId: (SearchHistory object) => object.id,
      setId: (SearchHistory object, int id) {
        object.id = id;
      },
      objectToFB: (SearchHistory object, fb.Builder fbb) {
        final queryOffset = fbb.writeString(object.query);
        final queryEmbeddingOffset = object.queryEmbedding == null
            ? null
            : fbb.writeListFloat32(object.queryEmbedding!);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, queryOffset);
        fbb.addOffset(2, queryEmbeddingOffset);
        fbb.addInt64(3, object.searchedAt.millisecondsSinceEpoch);
        fbb.addInt64(4, object.resultCount);
        fbb.addBool(5, object.hasClicked);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final queryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final queryEmbeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final searchedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final resultCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final hasClickedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final object = SearchHistory(
          id: idParam,
          query: queryParam,
          queryEmbedding: queryEmbeddingParam,
          searchedAt: searchedAtParam,
          resultCount: resultCountParam,
          hasClicked: hasClickedParam,
        );

        return object;
      },
    ),
    SimilarNotesCache: obx_int.EntityDefinition<SimilarNotesCache>(
      model: _entities[2],
      toOneRelations: (SimilarNotesCache object) => [],
      toManyRelations: (SimilarNotesCache object) => {},
      getId: (SimilarNotesCache object) => object.id,
      setId: (SimilarNotesCache object, int id) {
        object.id = id;
      },
      objectToFB: (SimilarNotesCache object, fb.Builder fbb) {
        final sourceNoteIdOffset = fbb.writeString(object.sourceNoteId);
        final similarNoteIdsJsonOffset = fbb.writeString(
          object.similarNoteIdsJson,
        );
        final similarityScoresJsonOffset = fbb.writeString(
          object.similarityScoresJson,
        );
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, sourceNoteIdOffset);
        fbb.addOffset(2, similarNoteIdsJsonOffset);
        fbb.addOffset(3, similarityScoresJsonOffset);
        fbb.addInt64(4, object.cachedAt.millisecondsSinceEpoch);
        fbb.addInt64(5, object.validHours);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final sourceNoteIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final similarNoteIdsJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final similarityScoresJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final cachedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final validHoursParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final object = SimilarNotesCache(
          id: idParam,
          sourceNoteId: sourceNoteIdParam,
          similarNoteIdsJson: similarNoteIdsJsonParam,
          similarityScoresJson: similarityScoresJsonParam,
          cachedAt: cachedAtParam,
          validHours: validHoursParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [NoteVector] entity fields to define ObjectBox queries.
class NoteVector_ {
  /// See [NoteVector.id].
  static final id = obx.QueryIntegerProperty<NoteVector>(
    _entities[0].properties[0],
  );

  /// See [NoteVector.noteId].
  static final noteId = obx.QueryStringProperty<NoteVector>(
    _entities[0].properties[1],
  );

  /// See [NoteVector.embedding].
  static final embedding = obx.QueryHnswProperty<NoteVector>(
    _entities[0].properties[2],
  );

  /// See [NoteVector.contentPreview].
  static final contentPreview = obx.QueryStringProperty<NoteVector>(
    _entities[0].properties[3],
  );

  /// See [NoteVector.createdAt].
  static final createdAt = obx.QueryDateProperty<NoteVector>(
    _entities[0].properties[4],
  );

  /// See [NoteVector.updatedAt].
  static final updatedAt = obx.QueryDateProperty<NoteVector>(
    _entities[0].properties[5],
  );

  /// See [NoteVector.modelVersion].
  static final modelVersion = obx.QueryStringProperty<NoteVector>(
    _entities[0].properties[6],
  );

  /// See [NoteVector.dimension].
  static final dimension = obx.QueryIntegerProperty<NoteVector>(
    _entities[0].properties[7],
  );
}

/// [SearchHistory] entity fields to define ObjectBox queries.
class SearchHistory_ {
  /// See [SearchHistory.id].
  static final id = obx.QueryIntegerProperty<SearchHistory>(
    _entities[1].properties[0],
  );

  /// See [SearchHistory.query].
  static final query = obx.QueryStringProperty<SearchHistory>(
    _entities[1].properties[1],
  );

  /// See [SearchHistory.queryEmbedding].
  static final queryEmbedding = obx.QueryDoubleVectorProperty<SearchHistory>(
    _entities[1].properties[2],
  );

  /// See [SearchHistory.searchedAt].
  static final searchedAt = obx.QueryDateProperty<SearchHistory>(
    _entities[1].properties[3],
  );

  /// See [SearchHistory.resultCount].
  static final resultCount = obx.QueryIntegerProperty<SearchHistory>(
    _entities[1].properties[4],
  );

  /// See [SearchHistory.hasClicked].
  static final hasClicked = obx.QueryBooleanProperty<SearchHistory>(
    _entities[1].properties[5],
  );
}

/// [SimilarNotesCache] entity fields to define ObjectBox queries.
class SimilarNotesCache_ {
  /// See [SimilarNotesCache.id].
  static final id = obx.QueryIntegerProperty<SimilarNotesCache>(
    _entities[2].properties[0],
  );

  /// See [SimilarNotesCache.sourceNoteId].
  static final sourceNoteId = obx.QueryStringProperty<SimilarNotesCache>(
    _entities[2].properties[1],
  );

  /// See [SimilarNotesCache.similarNoteIdsJson].
  static final similarNoteIdsJson = obx.QueryStringProperty<SimilarNotesCache>(
    _entities[2].properties[2],
  );

  /// See [SimilarNotesCache.similarityScoresJson].
  static final similarityScoresJson =
      obx.QueryStringProperty<SimilarNotesCache>(_entities[2].properties[3]);

  /// See [SimilarNotesCache.cachedAt].
  static final cachedAt = obx.QueryDateProperty<SimilarNotesCache>(
    _entities[2].properties[4],
  );

  /// See [SimilarNotesCache.validHours].
  static final validHours = obx.QueryIntegerProperty<SimilarNotesCache>(
    _entities[2].properties[5],
  );
}
