# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. Are you running flutter pub get inside the Flutter project?"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.+)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # 对特定target进行配置
    target.build_configurations.each do |config|
      # 设置iOS部署目标
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      
      # 禁用Bitcode
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      
      # 设置Swift版本
      config.build_settings['SWIFT_VERSION'] = '5.0'
      
      # 设置Swift编译器标志
      config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone' if config.name == 'Debug'
      
      # 设置C++标准库
      config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
      
      # 设置C++标准
      config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++0x'
    end
  end
end
