// Mocks generated by Mockito 5.4.6 from annotations
// in thoughtecho/test/unit/controllers/add_note_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i9;

import 'package:flutter/material.dart' as _i2;
import 'package:geolocator/geolocator.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:sqflite/sqflite.dart' as _i3;
import 'package:thoughtecho/gen_l10n/app_localizations.dart' as _i12;
import 'package:thoughtecho/models/merge_report.dart' as _i4;
import 'package:thoughtecho/models/note_category.dart' as _i15;
import 'package:thoughtecho/models/quote_model.dart' as _i14;
import 'package:thoughtecho/services/database_service.dart' as _i13;
import 'package:thoughtecho/services/location_service.dart' as _i5;
import 'package:thoughtecho/services/weather_cache_manager.dart' as _i11;
import 'package:thoughtecho/services/weather_service.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeIconData_0 extends _i1.SmartFake implements _i2.IconData {
  _FakeIconData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabase_1 extends _i1.SmartFake implements _i3.Database {
  _FakeDatabase_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMergeReport_2 extends _i1.SmartFake implements _i4.MergeReport {
  _FakeMergeReport_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i5.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasLocationPermission => (super.noSuchMethod(
        Invocation.getter(#hasLocationPermission),
        returnValue: false,
      ) as bool);

  @override
  bool get isLocationServiceEnabled => (super.noSuchMethod(
        Invocation.getter(#isLocationServiceEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  List<_i5.CityInfo> get searchResults => (super.noSuchMethod(
        Invocation.getter(#searchResults),
        returnValue: <_i5.CityInfo>[],
      ) as List<_i5.CityInfo>);

  @override
  bool get isSearching => (super.noSuchMethod(
        Invocation.getter(#isSearching),
        returnValue: false,
      ) as bool);

  @override
  bool get isOfflineLocation => (super.noSuchMethod(
        Invocation.getter(#isOfflineLocation),
        returnValue: false,
      ) as bool);

  @override
  bool get hasCoordinates => (super.noSuchMethod(
        Invocation.getter(#hasCoordinates),
        returnValue: false,
      ) as bool);

  @override
  set currentLocaleCode(String? code) => super.noSuchMethod(
        Invocation.setter(
          #currentLocaleCode,
          code,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> checkLocationPermission() => (super.noSuchMethod(
        Invocation.method(
          #checkLocationPermission,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> requestLocationPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestLocationPermission,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> refreshServiceStatus() => (super.noSuchMethod(
        Invocation.method(
          #refreshServiceStatus,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i7.Position?> getCurrentLocation({
    bool? highAccuracy = false,
    bool? skipPermissionRequest = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentLocation,
          [],
          {
            #highAccuracy: highAccuracy,
            #skipPermissionRequest: skipPermissionRequest,
          },
        ),
        returnValue: _i6.Future<_i7.Position?>.value(),
      ) as _i6.Future<_i7.Position?>);

  @override
  _i6.Future<void> getAddressFromLatLng() => (super.noSuchMethod(
        Invocation.method(
          #getAddressFromLatLng,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> refreshAddressFromOnlineReverseGeocoding() =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshAddressFromOnlineReverseGeocoding,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<List<_i5.CityInfo>> searchCity(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchCity,
          [query],
        ),
        returnValue: _i6.Future<List<_i5.CityInfo>>.value(<_i5.CityInfo>[]),
      ) as _i6.Future<List<_i5.CityInfo>>);

  @override
  void clearSearchResults() => super.noSuchMethod(
        Invocation.method(
          #clearSearchResults,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> setSelectedCity(_i5.CityInfo? city) => (super.noSuchMethod(
        Invocation.method(
          #setSelectedCity,
          [city],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  String getFormattedLocation() => (super.noSuchMethod(
        Invocation.method(
          #getFormattedLocation,
          [],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #getFormattedLocation,
            [],
          ),
        ),
      ) as String);

  @override
  String getDisplayLocation() => (super.noSuchMethod(
        Invocation.method(
          #getDisplayLocation,
          [],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #getDisplayLocation,
            [],
          ),
        ),
      ) as String);

  @override
  String getLocationDisplayText() => (super.noSuchMethod(
        Invocation.method(
          #getLocationDisplayText,
          [],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #getLocationDisplayText,
            [],
          ),
        ),
      ) as String);

  @override
  void setCoordinates(
    double? latitude,
    double? longitude, {
    String? address,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setCoordinates,
          [
            latitude,
            longitude,
          ],
          {#address: address},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<bool> resolveOfflineLocation() => (super.noSuchMethod(
        Invocation.method(
          #resolveOfflineLocation,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  void parseLocationString(String? locationString) => super.noSuchMethod(
        Invocation.method(
          #parseLocationString,
          [locationString],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [WeatherService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherService extends _i1.Mock implements _i10.WeatherService {
  MockWeatherService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.WeatherServiceState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i10.WeatherServiceState.idle,
      ) as _i10.WeatherServiceState);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasData => (super.noSuchMethod(
        Invocation.getter(#hasData),
        returnValue: false,
      ) as bool);

  @override
  bool get hasValidWeatherData => (super.noSuchMethod(
        Invocation.getter(#hasValidWeatherData),
        returnValue: false,
      ) as bool);

  @override
  set cacheManagerForTesting(_i11.WeatherCacheManager? manager) =>
      super.noSuchMethod(
        Invocation.setter(
          #cacheManagerForTesting,
          manager,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> getWeatherData(
    double? latitude,
    double? longitude, {
    bool? forceRefresh = false,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeatherData,
          [
            latitude,
            longitude,
          ],
          {
            #forceRefresh: forceRefresh,
            #timeout: timeout,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> refreshWeather(
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshWeather,
          [
            latitude,
            longitude,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void resetWeatherState() => super.noSuchMethod(
        Invocation.method(
          #resetWeatherState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getFormattedWeather(_i12.AppLocalizations? l10n) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFormattedWeather,
          [l10n],
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #getFormattedWeather,
            [l10n],
          ),
        ),
      ) as String);

  @override
  _i2.IconData getWeatherIconData() => (super.noSuchMethod(
        Invocation.method(
          #getWeatherIconData,
          [],
        ),
        returnValue: _FakeIconData_0(
          this,
          Invocation.method(
            #getWeatherIconData,
            [],
          ),
        ),
      ) as _i2.IconData);

  @override
  _i6.Future<Map<String, dynamic>?> getCacheInfo() => (super.noSuchMethod(
        Invocation.method(
          #getCacheInfo,
          [],
        ),
        returnValue: _i6.Future<Map<String, dynamic>?>.value(),
      ) as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void setMockWeatherData() => super.noSuchMethod(
        Invocation.method(
          #setMockWeatherData,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i13.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasMoreQuotes => (super.noSuchMethod(
        Invocation.getter(#hasMoreQuotes),
        returnValue: false,
      ) as bool);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i3.Database get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeDatabase_1(
          this,
          Invocation.getter(#database),
        ),
      ) as _i3.Database);

  @override
  _i6.Future<_i3.Database> get safeDatabase => (super.noSuchMethod(
        Invocation.getter(#safeDatabase),
        returnValue: _i6.Future<_i3.Database>.value(_FakeDatabase_1(
          this,
          Invocation.getter(#safeDatabase),
        )),
      ) as _i6.Future<_i3.Database>);

  @override
  set onLocalDataChanged(_i9.VoidCallback? value) => super.noSuchMethod(
        Invocation.setter(
          #onLocalDataChanged,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> addQuote(_i14.Quote? quote) => (super.noSuchMethod(
        Invocation.method(
          #addQuote,
          [quote],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i14.Quote?> getQuoteById(
    String? id, {
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuoteById,
          [id],
          {#includeDeleted: includeDeleted},
        ),
        returnValue: _i6.Future<_i14.Quote?>.value(),
      ) as _i6.Future<_i14.Quote?>);

  @override
  _i6.Future<List<_i14.Quote>> getAllQuotes({
    bool? excludeHiddenNotes = true,
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllQuotes,
          [],
          {
            #excludeHiddenNotes: excludeHiddenNotes,
            #includeDeleted: includeDeleted,
          },
        ),
        returnValue: _i6.Future<List<_i14.Quote>>.value(<_i14.Quote>[]),
      ) as _i6.Future<List<_i14.Quote>>);

  @override
  _i6.Future<List<_i14.Quote>> getQuotesForPeriod(
    DateTime? start,
    DateTime? end, {
    bool? excludeHiddenNotes = true,
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuotesForPeriod,
          [
            start,
            end,
          ],
          {
            #excludeHiddenNotes: excludeHiddenNotes,
            #includeDeleted: includeDeleted,
          },
        ),
        returnValue: _i6.Future<List<_i14.Quote>>.value(<_i14.Quote>[]),
      ) as _i6.Future<List<_i14.Quote>>);

  @override
  _i6.Future<void> deleteQuote(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteQuote,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i14.Quote>> searchQuotesByContent(
    String? query, {
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchQuotesByContent,
          [query],
          {#includeDeleted: includeDeleted},
        ),
        returnValue: _i6.Future<List<_i14.Quote>>.value(<_i14.Quote>[]),
      ) as _i6.Future<List<_i14.Quote>>);

  @override
  _i6.Future<_i13.QuoteUpdateResult> updateQuote(_i14.Quote? quote) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateQuote,
          [quote],
        ),
        returnValue: _i6.Future<_i13.QuoteUpdateResult>.value(
            _i13.QuoteUpdateResult.updated),
      ) as _i6.Future<_i13.QuoteUpdateResult>);

  @override
  _i6.Future<int> batchUpdatePendingLocations({
    required String? resolvedAddress,
    int? hours = 24,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUpdatePendingLocations,
          [],
          {
            #resolvedAddress: resolvedAddress,
            #hours: hours,
          },
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<List<_i14.Quote>> getUserQuotes({
    List<String>? tagIds,
    String? categoryId,
    int? offset = 0,
    int? limit = 10,
    String? orderBy = 'date DESC',
    String? searchQuery,
    List<String>? selectedWeathers,
    List<String>? selectedDayPeriods,
    bool? excludeHiddenNotes = true,
    String? dateStart,
    String? dateEnd,
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserQuotes,
          [],
          {
            #tagIds: tagIds,
            #categoryId: categoryId,
            #offset: offset,
            #limit: limit,
            #orderBy: orderBy,
            #searchQuery: searchQuery,
            #selectedWeathers: selectedWeathers,
            #selectedDayPeriods: selectedDayPeriods,
            #excludeHiddenNotes: excludeHiddenNotes,
            #dateStart: dateStart,
            #dateEnd: dateEnd,
            #includeDeleted: includeDeleted,
          },
        ),
        returnValue: _i6.Future<List<_i14.Quote>>.value(<_i14.Quote>[]),
      ) as _i6.Future<List<_i14.Quote>>);

  @override
  _i6.Future<List<_i14.Quote>> getQuotesForSmartPush({
    int? limit = 200,
    String? orderBy = 'q.date DESC',
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuotesForSmartPush,
          [],
          {
            #limit: limit,
            #orderBy: orderBy,
            #includeDeleted: includeDeleted,
          },
        ),
        returnValue: _i6.Future<List<_i14.Quote>>.value(<_i14.Quote>[]),
      ) as _i6.Future<List<_i14.Quote>>);

  @override
  _i6.Future<int> getQuotesCount({
    List<String>? tagIds,
    String? categoryId,
    String? searchQuery,
    List<String>? selectedWeathers,
    List<String>? selectedDayPeriods,
    bool? excludeHiddenNotes = true,
    String? dateStart,
    String? dateEnd,
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getQuotesCount,
          [],
          {
            #tagIds: tagIds,
            #categoryId: categoryId,
            #searchQuery: searchQuery,
            #selectedWeathers: selectedWeathers,
            #selectedDayPeriods: selectedDayPeriods,
            #excludeHiddenNotes: excludeHiddenNotes,
            #dateStart: dateStart,
            #dateEnd: dateEnd,
            #includeDeleted: includeDeleted,
          },
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<List<_i14.Quote>> getDeletedQuotes({
    int? offset = 0,
    int? limit = 20,
    String? orderBy = 'deleted_at DESC',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDeletedQuotes,
          [],
          {
            #offset: offset,
            #limit: limit,
            #orderBy: orderBy,
          },
        ),
        returnValue: _i6.Future<List<_i14.Quote>>.value(<_i14.Quote>[]),
      ) as _i6.Future<List<_i14.Quote>>);

  @override
  _i6.Future<int> getDeletedQuotesCount() => (super.noSuchMethod(
        Invocation.method(
          #getDeletedQuotesCount,
          [],
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getTombstonesForBackup() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTombstonesForBackup,
          [],
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<void> restoreQuote(String? id) => (super.noSuchMethod(
        Invocation.method(
          #restoreQuote,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> permanentlyDeleteQuote(String? id) => (super.noSuchMethod(
        Invocation.method(
          #permanentlyDeleteQuote,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> emptyTrash() => (super.noSuchMethod(
        Invocation.method(
          #emptyTrash,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<int> autoCleanupExpiredTrash({required int? retentionDays}) =>
      (super.noSuchMethod(
        Invocation.method(
          #autoCleanupExpiredTrash,
          [],
          {#retentionDays: retentionDays},
        ),
        returnValue: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<void> incrementFavoriteCount(String? quoteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #incrementFavoriteCount,
          [quoteId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> resetFavoriteCount(String? quoteId) => (super.noSuchMethod(
        Invocation.method(
          #resetFavoriteCount,
          [quoteId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i14.Quote>> getMostFavoritedQuotesThisWeek(
          {int? limit = 5}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMostFavoritedQuotesThisWeek,
          [],
          {#limit: limit},
        ),
        returnValue: _i6.Future<List<_i14.Quote>>.value(<_i14.Quote>[]),
      ) as _i6.Future<List<_i14.Quote>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getAllCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCategories,
          [],
        ),
        returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<List<_i15.NoteCategory>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue:
            _i6.Future<List<_i15.NoteCategory>>.value(<_i15.NoteCategory>[]),
      ) as _i6.Future<List<_i15.NoteCategory>>);

  @override
  _i6.Future<void> addCategory(
    String? name, {
    String? iconName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCategory,
          [name],
          {#iconName: iconName},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> addCategoryWithId(
    String? id,
    String? name, {
    String? iconName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addCategoryWithId,
          [
            id,
            name,
          ],
          {#iconName: iconName},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Stream<List<_i15.NoteCategory>> watchCategories() => (super.noSuchMethod(
        Invocation.method(
          #watchCategories,
          [],
        ),
        returnValue: _i6.Stream<List<_i15.NoteCategory>>.empty(),
      ) as _i6.Stream<List<_i15.NoteCategory>>);

  @override
  _i6.Future<void> deleteCategory(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCategory,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateCategory(
    String? id,
    String? name, {
    String? iconName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCategory,
          [
            id,
            name,
          ],
          {#iconName: iconName},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i15.NoteCategory?> getCategoryById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategoryById,
          [id],
        ),
        returnValue: _i6.Future<_i15.NoteCategory?>.value(),
      ) as _i6.Future<_i15.NoteCategory?>);

  @override
  _i6.Future<void> initDefaultHitokotoCategories() => (super.noSuchMethod(
        Invocation.method(
          #initDefaultHitokotoCategories,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i15.NoteCategory?> getOrCreateHiddenTag() => (super.noSuchMethod(
        Invocation.method(
          #getOrCreateHiddenTag,
          [],
        ),
        returnValue: _i6.Future<_i15.NoteCategory?>.value(),
      ) as _i6.Future<_i15.NoteCategory?>);

  @override
  bool isHiddenTag(String? tagId) => (super.noSuchMethod(
        Invocation.method(
          #isHiddenTag,
          [tagId],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> removeHiddenTag() => (super.noSuchMethod(
        Invocation.method(
          #removeHiddenTag,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> isQuoteHidden(String? quoteId) => (super.noSuchMethod(
        Invocation.method(
          #isQuoteHidden,
          [quoteId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<List<String>> getHiddenQuoteIds() => (super.noSuchMethod(
        Invocation.method(
          #getHiddenQuoteIds,
          [],
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);

  @override
  void refreshQuotes() => super.noSuchMethod(
        Invocation.method(
          #refreshQuotes,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Stream<List<_i14.Quote>> watchQuotes({
    List<String>? tagIds,
    String? categoryId,
    int? limit = 20,
    String? orderBy = 'date DESC',
    String? searchQuery,
    List<String>? selectedWeathers,
    List<String>? selectedDayPeriods,
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchQuotes,
          [],
          {
            #tagIds: tagIds,
            #categoryId: categoryId,
            #limit: limit,
            #orderBy: orderBy,
            #searchQuery: searchQuery,
            #selectedWeathers: selectedWeathers,
            #selectedDayPeriods: selectedDayPeriods,
            #includeDeleted: includeDeleted,
          },
        ),
        returnValue: _i6.Stream<List<_i14.Quote>>.empty(),
      ) as _i6.Stream<List<_i14.Quote>>);

  @override
  _i6.Future<void> loadMoreQuotes({
    List<String>? tagIds,
    String? categoryId,
    String? searchQuery,
    List<String>? selectedWeathers,
    List<String>? selectedDayPeriods,
    bool? includeDeleted,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadMoreQuotes,
          [],
          {
            #tagIds: tagIds,
            #categoryId: categoryId,
            #searchQuery: searchQuery,
            #selectedWeathers: selectedWeathers,
            #selectedDayPeriods: selectedDayPeriods,
            #includeDeleted: includeDeleted,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> importDataFromMap(
    Map<String, dynamic>? data, {
    bool? clearExisting = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #importDataFromMap,
          [data],
          {#clearExisting: clearExisting},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> importData(
    String? filePath, {
    bool? clearExisting = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #importData,
          [filePath],
          {#clearExisting: clearExisting},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> checkCanExport() => (super.noSuchMethod(
        Invocation.method(
          #checkCanExport,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> validateBackupFile(String? filePath) => (super.noSuchMethod(
        Invocation.method(
          #validateBackupFile,
          [filePath],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<_i4.MergeReport> importDataWithLWWMerge(
    Map<String, dynamic>? data, {
    String? sourceDevice,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #importDataWithLWWMerge,
          [data],
          {#sourceDevice: sourceDevice},
        ),
        returnValue: _i6.Future<_i4.MergeReport>.value(_FakeMergeReport_2(
          this,
          Invocation.method(
            #importDataWithLWWMerge,
            [data],
            {#sourceDevice: sourceDevice},
          ),
        )),
      ) as _i6.Future<_i4.MergeReport>);

  @override
  _i6.Future<void> patchQuotesDayPeriod() => (super.noSuchMethod(
        Invocation.method(
          #patchQuotesDayPeriod,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> migrateDayPeriodToKey() => (super.noSuchMethod(
        Invocation.method(
          #migrateDayPeriodToKey,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> migrateWeatherToKey() => (super.noSuchMethod(
        Invocation.method(
          #migrateWeatherToKey,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<Map<String, dynamic>> checkTagDataConsistency() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkTagDataConsistency,
          [],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<bool> cleanupTagDataInconsistencies() => (super.noSuchMethod(
        Invocation.method(
          #cleanupTagDataInconsistencies,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<List<int>> getHourDistributionForSmartPush() =>
      (super.noSuchMethod(
        Invocation.method(
          #getHourDistributionForSmartPush,
          [],
        ),
        returnValue: _i6.Future<List<int>>.value(<int>[]),
      ) as _i6.Future<List<int>>);

  @override
  Map<String, dynamic> getQueryPerformanceReport() => (super.noSuchMethod(
        Invocation.method(
          #getQueryPerformanceReport,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i6.Future<Map<String, dynamic>?> getLocalDailyQuote(
          {String? offlineQuoteSource = 'tagOnly'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocalDailyQuote,
          [],
          {#offlineQuoteSource: offlineQuoteSource},
        ),
        returnValue: _i6.Future<Map<String, dynamic>?>.value(),
      ) as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<Map<String, dynamic>> performDatabaseMaintenance(
          {dynamic Function(String)? onProgress}) =>
      (super.noSuchMethod(
        Invocation.method(
          #performDatabaseMaintenance,
          [],
          {#onProgress: onProgress},
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<Map<String, dynamic>> getDatabaseHealthInfo() =>
      (super.noSuchMethod(
        Invocation.method(
          #getDatabaseHealthInfo,
          [],
        ),
        returnValue:
            _i6.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i6.Future<Map<String, dynamic>>);

  @override
  String sanitizeOrderBy(
    String? orderBy, {
    String? prefix = '',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sanitizeOrderBy,
          [orderBy],
          {#prefix: prefix},
        ),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.method(
            #sanitizeOrderBy,
            [orderBy],
            {#prefix: prefix},
          ),
        ),
      ) as String);

  @override
  void clearAllCacheForParts() => super.noSuchMethod(
        Invocation.method(
          #clearAllCacheForParts,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void refreshQuotesStreamForParts() => super.noSuchMethod(
        Invocation.method(
          #refreshQuotesStreamForParts,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void scheduleCacheCleanupForParts() => super.noSuchMethod(
        Invocation.method(
          #scheduleCacheCleanupForParts,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> updateCategoriesStreamForParts() => (super.noSuchMethod(
        Invocation.method(
          #updateCategoriesStreamForParts,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void safeNotifyQuotesStreamForParts() => super.noSuchMethod(
        Invocation.method(
          #safeNotifyQuotesStreamForParts,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> initForBackgroundReadOnly() => (super.noSuchMethod(
        Invocation.method(
          #initForBackgroundReadOnly,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> initializeNewDatabase() => (super.noSuchMethod(
        Invocation.method(
          #initializeNewDatabase,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void refreshAllData() => super.noSuchMethod(
        Invocation.method(
          #refreshAllData,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void reinitialize() => super.noSuchMethod(
        Invocation.method(
          #reinitialize,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyLocalDataChangedForParts() => super.noSuchMethod(
        Invocation.method(
          #notifyLocalDataChangedForParts,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
