// Mocks generated by Mockito 5.4.6 from annotations
// in thoughtecho/test/unit/controllers/weather_search_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i7;

import 'package:flutter/material.dart' as _i2;
import 'package:geolocator/geolocator.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:thoughtecho/gen_l10n/app_localizations.dart' as _i10;
import 'package:thoughtecho/services/location_service.dart' as _i3;
import 'package:thoughtecho/services/weather_cache_manager.dart' as _i9;
import 'package:thoughtecho/services/weather_service.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeIconData_0 extends _i1.SmartFake implements _i2.IconData {
  _FakeIconData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i3.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasLocationPermission => (super.noSuchMethod(
        Invocation.getter(#hasLocationPermission),
        returnValue: false,
      ) as bool);

  @override
  bool get isLocationServiceEnabled => (super.noSuchMethod(
        Invocation.getter(#isLocationServiceEnabled),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  List<_i3.CityInfo> get searchResults => (super.noSuchMethod(
        Invocation.getter(#searchResults),
        returnValue: <_i3.CityInfo>[],
      ) as List<_i3.CityInfo>);

  @override
  bool get isSearching => (super.noSuchMethod(
        Invocation.getter(#isSearching),
        returnValue: false,
      ) as bool);

  @override
  bool get isOfflineLocation => (super.noSuchMethod(
        Invocation.getter(#isOfflineLocation),
        returnValue: false,
      ) as bool);

  @override
  bool get hasCoordinates => (super.noSuchMethod(
        Invocation.getter(#hasCoordinates),
        returnValue: false,
      ) as bool);

  @override
  set currentLocaleCode(String? code) => super.noSuchMethod(
        Invocation.setter(
          #currentLocaleCode,
          code,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> checkLocationPermission() => (super.noSuchMethod(
        Invocation.method(
          #checkLocationPermission,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> requestLocationPermission() => (super.noSuchMethod(
        Invocation.method(
          #requestLocationPermission,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> refreshServiceStatus() => (super.noSuchMethod(
        Invocation.method(
          #refreshServiceStatus,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.Position?> getCurrentLocation({
    bool? highAccuracy = false,
    bool? skipPermissionRequest = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentLocation,
          [],
          {
            #highAccuracy: highAccuracy,
            #skipPermissionRequest: skipPermissionRequest,
          },
        ),
        returnValue: _i4.Future<_i5.Position?>.value(),
      ) as _i4.Future<_i5.Position?>);

  @override
  _i4.Future<void> getAddressFromLatLng() => (super.noSuchMethod(
        Invocation.method(
          #getAddressFromLatLng,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> refreshAddressFromOnlineReverseGeocoding() =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshAddressFromOnlineReverseGeocoding,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<List<_i3.CityInfo>> searchCity(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchCity,
          [query],
        ),
        returnValue: _i4.Future<List<_i3.CityInfo>>.value(<_i3.CityInfo>[]),
      ) as _i4.Future<List<_i3.CityInfo>>);

  @override
  void clearSearchResults() => super.noSuchMethod(
        Invocation.method(
          #clearSearchResults,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> setSelectedCity(_i3.CityInfo? city) => (super.noSuchMethod(
        Invocation.method(
          #setSelectedCity,
          [city],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  String getFormattedLocation() => (super.noSuchMethod(
        Invocation.method(
          #getFormattedLocation,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getFormattedLocation,
            [],
          ),
        ),
      ) as String);

  @override
  String getDisplayLocation() => (super.noSuchMethod(
        Invocation.method(
          #getDisplayLocation,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getDisplayLocation,
            [],
          ),
        ),
      ) as String);

  @override
  String getLocationDisplayText() => (super.noSuchMethod(
        Invocation.method(
          #getLocationDisplayText,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getLocationDisplayText,
            [],
          ),
        ),
      ) as String);

  @override
  void setCoordinates(
    double? latitude,
    double? longitude, {
    String? address,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setCoordinates,
          [
            latitude,
            longitude,
          ],
          {#address: address},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<bool> resolveOfflineLocation() => (super.noSuchMethod(
        Invocation.method(
          #resolveOfflineLocation,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  void parseLocationString(String? locationString) => super.noSuchMethod(
        Invocation.method(
          #parseLocationString,
          [locationString],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [WeatherService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherService extends _i1.Mock implements _i8.WeatherService {
  MockWeatherService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.WeatherServiceState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i8.WeatherServiceState.idle,
      ) as _i8.WeatherServiceState);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasData => (super.noSuchMethod(
        Invocation.getter(#hasData),
        returnValue: false,
      ) as bool);

  @override
  bool get hasValidWeatherData => (super.noSuchMethod(
        Invocation.getter(#hasValidWeatherData),
        returnValue: false,
      ) as bool);

  @override
  set cacheManagerForTesting(_i9.WeatherCacheManager? manager) =>
      super.noSuchMethod(
        Invocation.setter(
          #cacheManagerForTesting,
          manager,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> getWeatherData(
    double? latitude,
    double? longitude, {
    bool? forceRefresh = false,
    Duration? timeout,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeatherData,
          [
            latitude,
            longitude,
          ],
          {
            #forceRefresh: forceRefresh,
            #timeout: timeout,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> refreshWeather(
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshWeather,
          [
            latitude,
            longitude,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void resetWeatherState() => super.noSuchMethod(
        Invocation.method(
          #resetWeatherState,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getFormattedWeather(_i10.AppLocalizations? l10n) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFormattedWeather,
          [l10n],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getFormattedWeather,
            [l10n],
          ),
        ),
      ) as String);

  @override
  _i2.IconData getWeatherIconData() => (super.noSuchMethod(
        Invocation.method(
          #getWeatherIconData,
          [],
        ),
        returnValue: _FakeIconData_0(
          this,
          Invocation.method(
            #getWeatherIconData,
            [],
          ),
        ),
      ) as _i2.IconData);

  @override
  _i4.Future<Map<String, dynamic>?> getCacheInfo() => (super.noSuchMethod(
        Invocation.method(
          #getCacheInfo,
          [],
        ),
        returnValue: _i4.Future<Map<String, dynamic>?>.value(),
      ) as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void setMockWeatherData() => super.noSuchMethod(
        Invocation.method(
          #setMockWeatherData,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
