name: Simplified Flutter Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  checks: write

env:
  FLUTTER_VERSION: '3.35.3'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        cache: true

    - name: Get dependencies
      run: flutter pub get

    - name: Run tests
      run: flutter test --reporter compact --timeout 180s

    - name: Check formatting and analysis
      run: |
        dart format --set-exit-if-changed .
        flutter analyze --fatal-infos