// Mock file for NoteSyncPage tests
// This file should be generated by running:
// dart run build_runner build

// For now, we'll provide a minimal mock structure
import 'package:mockito/mockito.dart';
import 'package:thoughtecho/services/backup_service.dart';
import 'package:thoughtecho/services/database_service.dart';
import 'package:thoughtecho/services/settings_service.dart';
import 'package:thoughtecho/services/ai_analysis_database_service.dart';
import 'package:thoughtecho/services/note_sync_service.dart';

class MockDatabaseService extends Mock implements DatabaseService {}
class MockSettingsService extends Mock implements SettingsService {}
class MockAIAnalysisDatabaseService extends Mock implements AIAnalysisDatabaseService {}
class MockNoteSyncService extends Mock implements NoteSyncService {}
class MockBackupService extends Mock implements BackupService {}